# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: wiringbits
email: hello@wiringbits.net
description: >- # this means to ignore newlines until "baseurl:"
  A Mexican company producing great software mainly with Scala.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wiringbits.net"
# twitter_username: jekyllrb
github_username: wiringbits
google_analytics: UA-65008315-4

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme@2.5.1

minima:
  skin: classic

sass:
  sass_dir: _sass
  style: compressed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

testimonials:
  - author: Michael Bruny-Groth
    position: Logo Package Founder
    description: Alexis at Wiringbits has assembled a great team of development talent. Our project included web app development and niche Adobe extension development. We were delighted with the quality of service we received and would not hesitate to recommend Wiringbits for any web or software development.
    image: assets/home/testimonials/reviewer/michael-bruny.jpg
  - author: Cesar Diaz
    position: Bowhead Health CTO
    description: Wiringbits mobile development service was super helpful, they allowed us to extend the team in a very short time. Their availability to support us exceeded our expectations, they were able to add redundancy to the team in an emergency case, additionally they were always in constant communication with the Bowhead team in a professional and friendly way.
    image: assets/home/testimonials/reviewer/cesar-diaz.jpg